Integrated CWL support and Collections support (for both WDL and CWL)
qiime2/q2dataflow pull request #6
Opened 2023-10-16 19:16 UTC by AmandaBirmingham

This PR ports and extends the functionality of q2cwl (https://github.com/qiime2/q2cwl ) into the q2dataflow framework.  Additionally, it adds support for the new Collection type in both WDL and CWL.

I realize this is a rather giant PR.  If there are guidelines/suggestions on breaking it up to make it more readable, or if we should talk through it live before the review, let me know.

Notes for reviewers:
* I was unable to use conda to create an environment containing qiime2 release 2023.7, q2dataflow, miniwdl, *and* cwltool; conda started throwing unsolvable-conflict errors. Mamba, however, worked like a charm.
* The Dockerfile used for the WDL testing for this branch specifically references this branch's name; this will have to be changed before integration with main.
* Support for Collection[Artifact] inputs in WDL has been implemented, but cannot be effectively tested due to the miniwdl emulator's propensity to move inputs around and thus break relative paths.  Per discussion on Campfire, tests for this class of inputs are thus skipped and return a message to this effect.
* The handling of multiple-type inputs in both CWL and WDL depends on treating all inputs as strings at collection and using parse_primitives to figure out their "real" type on consumption by Qiime2. This strategy *will fail* for edge cases like, say, wanting to input the *string* "1.5" rather than the float `1.5`.  Earlier discussion indicated we could live with this limitation, but we should definitely keep it in mind.

Question for reviewers:
1) This does not port the docker-based entry point in q2cwl, only the conda-based one.  Is the docker one still needed?  It wasn't clear to me what its use-case is.
2) What is needed to update the CI for this project to integrate the CWL tests?

2023-10-17 17:15 UTC, ebolyen commented
Thanks @AmandaBirmingham, this is going to take me a bit to review. I will probably do it in multiple chunks over a few days. So I will report with a "finished reviewing" on the last one.

2023-11-20 17:41 UTC, ebolyen requested changes
Some immediate notes: the builtins don't quite work because the `spec` is initialized to `None` for the (manually created) case instances.

I like how the WdlParamCase base-class handles the collection question all at once, and I think we can do the same with CWL. I pointed out some minimal changes which technically fix the issue, but there's no obligation to actually use them.

Would there be utility in bumping this logic up into the root ParamCase?

2023-11-20 17:41 UTC, ebolyen commented on q2dataflow/languages/cwl/templaters/helpers.py
> +        self._is_file = self.spec.qiime_type.name != QIIME_COLLECTION_TYPE
```suggestion
        self._is_file = (
            self.spec is None 
            or self.spec.qiime_type.name != QIIME_COLLECTION_TYPE
        )
```

2023-11-20 17:41 UTC, ebolyen commented on q2dataflow/languages/cwl/templaters/helpers.py
> +        if self.spec.qiime_type.name == 'Collection':
```suggestion
        if self.spec is not None and self.spec.qiime_type.name == 'Collection':
```

2023-11-20 17:41 UTC, ebolyen commented on q2dataflow/languages/wdl/templaters/helpers.py
> +            self.spec.qiime_type.name == QIIME_COLLECTION_TYPE
```suggestion
        self._is_collection = (
            self.spec is not None
            and self.spec.qiime_type.name == QIIME_COLLECTION_TYPE
        )
```

2024-01-22 22:41 UTC, Oddant1 commented
@AmandaBirmingham Is this PR still in development?

2024-01-22 22:59 UTC, AmandaBirmingham commented
@Oddant1 Yes, my apologies, you will see a commit tomorrow!

2024-01-23 23:42 UTC, Oddant1 commented
@AmandaBirmingham All good! Just checking in.

2024-01-23 23:50 UTC, AmandaBirmingham commented
@ebolyen , I think you set up the CI for the wdl tests (which are hideous because they have to run through docker).  I have made the changes above, which (after rebuilding my docker image) allows me to successfully create templates for builtins on my local machine and also to run the WDL mystery stew tests.  However, on github the WDL unit tests are failing at the first test, saying `"docker image not found: testq2dataflow:latest"` ... do you have any idea what might lead to this issue in the CI environment?

2024-02-21 23:52 UTC, AmandaBirmingham commented
@ebolyen @Oddant1 Hi, Folks--a ping to see if either of you can help me figure out what the issue with the CI docker image generation/access is here?  The unit tests won't run (and pass and get this PR merged, I hope ;) because `miniwdl` reports a `"docker image not found: testq2dataflow:latest"` error.   AFAICT (which is not very far ...) it looks like the docker image is being created without error earlier in the CI, so I am unclear why its image isn't available at the later step.  I think the docker functionality in the github workflow was originally the magic of @ebolyen ... do you have any insight into what might be going weird here?

2024-02-22 23:42 UTC, ebolyen commented
Hey @AmandaBirmingham, unfortunately, I don't have any good insight here yet. But I will be overhauling some of our docker builds for our releases here in the next week, and I bet I can come up with a smarter way to handle this once I've tested a few things in that context.

2024-04-18 22:43 UTC, ebolyen commented
Tests are actually running!

2024-04-19 05:38 UTC, ebolyen commented on .github/workflows/ci_wdl.yml
>            pip install miniwdl
```suggestion
          pip install miniwdl cwlref-runner
```

2024-04-19 18:07 UTC, ebolyen commented on q2dataflow/core/signature_converter/util.py
> +    except KeyError:
duh... of course, thanks :)

I was just so baffled how the pluginmanager was already instantiated (turned out to be this: https://github.com/qiime2/q2cli/issues/334)

2024-04-19 18:09 UTC, ebolyen commented
```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/qiime2/bin/q2dataflow", line 5, in <module>
    from q2dataflow.__main__ import root
  File "/usr/share/miniconda/envs/qiime2/lib/python3.8/site-packages/q2dataflow/__main__.py", line 13, in <module>
    from q2dataflow.languages.wdl.templaters.helpers import \
ModuleNotFoundError: No module named 'q2dataflow.languages'
```
(From the last run)
This looks like a circular import not having a finalized module to me

2024-04-19 18:27 UTC, ebolyen commented
:tada: :tada: :tada:

2024-04-19 23:45 UTC, AmandaBirmingham commented
@ebolyen  All WDL and CWL tests pass (except for the ones intentionally skipped, of course :) :rocket:

2024-04-19 23:46 UTC, ebolyen approved these changes
Thanks so much @AmandaBirmingham!

2024-04-19 23:46 UTC, merged

2024-04-19 23:55 UTC, AmandaBirmingham commented
Yaay! Talk about a team effort! :raised_hands: